import { useState } from "react";
import { AlertTriangle, ArrowLeft, Cpu, History, MessageSquareWarning, ShieldCheck, Sparkles } from "lucide-react";

import Toast from "../common/Toast";
import { useToast } from "../../hooks/useToast";
import OverviewCard from "./ui/OverviewCard";
import AnalysisMain from "./AnalysisMain";
import AnalysisSidebar from "./AnalysisSidebar";
import CodeFixes from "./CodeFixes";

function AnalysisView({ analysis, inputText, selectedFile, filePreview, onBack, onBackHistory }) {
  const [copiedSection, setCopiedSection] = useState(null);
  const { message, showMessage } = useToast();

  const copyText = async (text, section) => {
    try {
      await navigator.clipboard.writeText(text);
      setCopiedSection(section);
      showMessage("success", "Copied to clipboard.");
      window.setTimeout(() => setCopiedSection(null), 1800);
    } catch {
      showMessage("error", "Unable to copy to clipboard.");
    }
  };

  if (!analysis) return null;

  return (
    <>
      <main className="py-10 sm:py-12 lg:py-14">
        <section className="mx-auto max-w-7xl">
          <div className="mb-7 flex items-center justify-between gap-3">
            <button type="button" onClick={onBackHistory} className="inline-flex items-center gap-2 rounded-xl border border-[var(--border)] bg-[var(--surface-solid)] px-4 py-2.5 text-sm font-semibold text-[var(--text-secondary)] shadow-sm transition-all duration-200 hover:-translate-y-0.5 hover:bg-[var(--surface-muted)] hover:text-[var(--text-primary)]"><History size={16} />Back to History</button>
            <button type="button" onClick={onBack} className="inline-flex items-center justify-center rounded-xl bg-blue-600 px-4 py-2.5 text-sm font-semibold text-white shadow-lg shadow-blue-600/20 transition-all duration-200 hover:-translate-y-0.5 hover:bg-blue-700">Analyze another error</button>
          </div>

          <div id="buglens-analysis-overview" className="mb-8">
            <div className="mb-3 inline-flex items-center gap-2 rounded-full border border-blue-500/10 bg-blue-500/10 px-3.5 py-1.5 text-xs font-semibold text-blue-600 dark:text-blue-400"><Sparkles size={14} />BugLens Analysis</div>
            <h1 className="text-3xl font-black tracking-tight sm:text-4xl">{analysis.title}</h1>
            <p className="mt-3 max-w-4xl text-sm leading-6 text-[var(--text-secondary)] sm:text-base">{analysis.summary}</p>
          </div>

          <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4">
            <OverviewCard icon={<MessageSquareWarning size={19} />} label="Bug type" value={analysis.bugType} />
            <OverviewCard icon={<AlertTriangle size={19} />} label="Severity" value={analysis.severity} danger />
            <OverviewCard icon={<ShieldCheck size={19} />} label="Confidence" value={`${analysis.confidence}%`} success />
            <OverviewCard icon={<Cpu size={19} />} label="Technology" value={`${analysis.language} · ${analysis.framework}`} />
          </div>

          <div className="mt-6 grid items-stretch gap-6 lg:grid-cols-[minmax(0,1fr)_360px]">
            <AnalysisMain analysis={analysis} />
            <AnalysisSidebar analysis={analysis} inputText={inputText} selectedFile={selectedFile} filePreview={filePreview} onCopyCommand={(command) => copyText(command, command)} />
          </div>

          <CodeFixes analysis={analysis} copiedSection={copiedSection} onCopy={copyText} />

          <div id="buglens-analysis-complete" className="mt-6 rounded-2xl border border-blue-500/10 bg-blue-500/5 p-5 sm:p-6">
            <div className="flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between">
              <div><div className="flex items-center gap-2"><Sparkles size={18} className="text-blue-600 dark:text-blue-400" /><h3 className="font-semibold">Analysis complete</h3></div><p className="mt-1 text-sm text-[var(--text-secondary)]">This result was generated by the BugLens backend using Groq.</p></div>
              <button type="button" onClick={onBack} className="inline-flex shrink-0 items-center justify-center gap-2 rounded-xl bg-blue-600 px-4 py-2.5 text-sm font-semibold text-white shadow-lg shadow-blue-600/20 transition hover:bg-blue-700"><ArrowLeft size={16} className="rotate-180" />Analyze another error</button>
            </div>
          </div>
        </section>
      </main>

      <Toast message={message} />
    </>
  );
}

export default AnalysisView;
